"""add parent posts

Revision ID: 80a2a8590de7
Revises: 85c7cb78b8f3
Create Date: 2020-08-18 12:32:49.718509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80a2a8590de7'
down_revision = '85c7cb78b8f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'post', 'post', ['parent_post'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    # ### end Alembic commands ###
